In [1]:
# Importing Tensorflow
import tensorflow as tf

In [2]:
# Tensorflow Version
print(tf.__version__)

1.8.0


In [3]:
# Declaring Variables in Tensorflow
x = tf.constant("Hello ")
y = tf.constant("World!")

In [4]:
x + y

<tf.Tensor 'add:0' shape=() dtype=string>

In [5]:
# Starting an Tensorflow Session for Computing Operations.
with tf.Session() as sess:
    result = sess.run(x + y)

In [6]:
print(result)

b'Hello World!'


In [7]:
a = tf.constant(10)
b = tf.constant(25)
print(a, type(a))
print(b, type(a))

Tensor("Const_2:0", shape=(), dtype=int32) <class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const_3:0", shape=(), dtype=int32) <class 'tensorflow.python.framework.ops.Tensor'>


In [8]:
with tf.Session() as sess:
    add = sess.run(a + b)
    sub = sess.run(a - b)
    mul = sess.run(a * b)
    div = sess.run(a / b)
    print(add, sub, mul, div)

35 -15 250 0.4


In [9]:
# Declaring Constants Matrices and Tensors
const = tf.constant(10)

# Tensor/Matrix with constant
fill_mat = tf.fill((4,4), 10)

# Tensor/Matrix with Zeros
zeros = tf.zeros((4,4))

# Tensor/Matrix with Normal Distribution
randn = tf.random_normal((4,4), mean = 0, stddev = 1.0)

# Tensor/Matrix with Unifor Distribution
randu = tf.random_uniform((4,4), minval = 0, maxval = 1)

In [10]:
my_vars = [const, fill_mat, zeros, randn, randu]

In [11]:
with tf.Session() as sess:
    for op in my_vars:
        print(type(sess.run(op)))
        print(sess.run(op), '\n')

<class 'numpy.int32'>
10 

<class 'numpy.ndarray'>
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

<class 'numpy.ndarray'>
[[-1.0055184  -0.71446925  0.07026308 -0.07863994]
 [ 0.36090484 -0.2632373  -0.28138337  1.0936038 ]
 [-0.6932135  -0.289206    0.42735472  0.8974102 ]
 [-1.24106     1.2422935   0.64866084  0.9574649 ]] 

<class 'numpy.ndarray'>
[[0.10063553 0.23404443 0.20927453 0.8755752 ]
 [0.98094    0.14995265 0.94381654 0.6617819 ]
 [0.7958274  0.13617575 0.02344024 0.6173439 ]
 [0.02743196 0.588102   0.23595452 0.8416462 ]] 



In [12]:
p = tf.constant([[1, 2],
                 [3, 4]])

In [13]:
p.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [14]:
q = tf.constant([[10],
                 [10]])

In [15]:
q.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [16]:
# All the cells under it are in Session Loop.
sess = tf.InteractiveSession()

In [17]:
result = tf.matmul(p, q)

In [18]:
sess.run(result)

array([[30],
       [70]], dtype=int32)