In [1]:
import tensorflow as tf

#### two main types of tensor objects in tensorflow.
1. **Variables**: 
Holds the values of weights and biases during the training process.
They need to be initialised. 
2. **Placeholders**:
Initially empty and are used to feed in actuall training examples.
The datatype of placeholders should be declared ecplicitly.

In [2]:
my_tensor = tf.random_uniform((4,4),minval=0, maxval=1)

In [3]:
my_tensor

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [4]:
my_var = tf.Variable(initial_value=my_tensor)

In [5]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [6]:
type(my_var)

tensorflow.python.ops.variables.Variable

In [7]:
# Gives Error Since the Variables must be initialised.
"""
 with tf.Session() as sess:
    sess.run(my_var)
"""

'\n with tf.Session() as sess:\n    sess.run(my_var)\n'

In [8]:
# initialising all the global variables
init = tf.global_variables_initializer()

In [9]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(my_var))

[[0.47781098 0.38366532 0.7287035  0.84541297]
 [0.80831563 0.21558356 0.15378761 0.876493  ]
 [0.48001325 0.20598495 0.3108436  0.20711482]
 [0.16314363 0.44267523 0.71942246 0.36936975]]


In [10]:
placeholder = tf.placeholder(tf.float32, shape = (4,4))

In [11]:
print(placeholder)

Tensor("Placeholder:0", shape=(4, 4), dtype=float32)


In [12]:
type(placeholder)

tensorflow.python.framework.ops.Tensor